### PR TITLE
Fix npm publish error:

### PR DESCRIPTION
**Pull request by ItzMiracleOwO**
Fix npm publish action error:
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/discordjs-activity - You cannot publish over the previously published versions: 1.4.1.

Changing version in package.json from 1.4.1 to 1.4.2

### CODE REVIEW

**Comment by SudhanPlayz** [comment]
check actions doesnt works

**Comment by ItzMiracleOwO** [comment]
Hi there

it is just an authentication issue with your token.

Have you ever set the access token in your Repository secrets ? (You might want to create environments as well.)

https://docs.npmjs.com/creating-and-viewing-access-tokens

Or it might be an issue with authorization as well. Please check your token type. It should be automation one.

@SudhanPlayz

**Comment by ItzMiracleOwO** [comment]
As what I see, the publish action never worked. So it should be a token issue

**Comment by SudhanPlayz** [comment]
ohhh, i will check it

**Comment by ItzMiracleOwO** [comment]
Sure :)

**Comment by ItzMiracleOwO** [comment]
@SudhanPlayz is it fixed? :3

**Pull request merged**
